# Generated by Django 6.0.3 on 2026-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_client_account_manager_client_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsite',
            name='access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='survey',
            name='site_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='survey',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
