# Generated by Django 6.0.3 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_name_survey_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
