# Generated by Django 6.0.3 on 2026-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_client_is_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsite',
            name='address',
        ),
        migrations.AddField(
            model_name='clientsite',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
