# Generated by Django 6.0.3 on 2026-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_add_is_demo_to_site_survey_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='survey',
            name='arrival_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='attendance_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('attended', 'Attended'), ('missed', 'Missed')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('missed', 'Missed'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='departure_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='notify_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='other_attendees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='schedule_status',
            field=models.CharField(blank=True, choices=[('self_scheduled', 'Self-scheduled'), ('provisional', 'Provisional'), ('booked', 'Booked')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='scheduled_status',
            field=models.CharField(blank=True, choices=[('self_scheduled', 'Self-scheduled'), ('provisional', 'Provisional'), ('confirmed', 'Confirmed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='site_requirements',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_date_status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled')], default='unscheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_record_status',
            field=models.CharField(choices=[('unarchived', 'Unarchived'), ('archived', 'Archived')], default='unarchived', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_weekends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='visit_requirement',
            field=models.CharField(blank=True, choices=[('24h_notify', '24 Hours - notify in advance'), ('24h_no_notify', '24 Hours - no notification'), ('wh_notify', 'Working hours - notify in advance'), ('wh_no_notify', 'Working hours - no notification'), ('prearranged', 'Pre-arranged visits only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='visit_time',
            field=models.CharField(blank=True, choices=[('anytime', 'Anytime'), ('window', 'Time window'), ('appointment', 'Appointment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_end_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_start_end_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='notify_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('visit', 'Visit'), ('revisit', 'Revisit'), ('review', 'Review')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
