# Generated by Django 4.2.16 on 2026-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_survey_observation_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
