# Generated by Django 4.2.16 on 2026-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_survey_client_survey_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='client_present',
            field=models.BooleanField(default=False),
        ),
    ]
