# Generated by Django 4.2.16 on 2026-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_survey_client_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
