# Generated by Django 4.2.16 on 2026-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_survey_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
