# Generated by Django 4.2.16 on 2026-03-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
