# Generated by Django 6.0.3 on 2026-03-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_client_alter_survey_client_clientcontact_clientsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='posts.client'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='posts.clientsite'),
        ),
    ]
