# Generated by Django 6.0.3 on 2026-03-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_survey_client_alter_survey_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('local_authority', 'Local authority'), ('education', 'Education'), ('retail', 'Retail'), ('residential', 'Residential portfolio')], max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='site_type',
            field=models.CharField(blank=True, choices=[('car_park', 'Car park'), ('retail_park', 'Retail park'), ('industrial_estate', 'Industrial estate'), ('school', 'School'), ('office_campus', 'Office campus')], max_length=30),
        ),
        migrations.AddField(
            model_name='clientsite',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
