# Generated by Django 6.0.3 on 2026-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='schedule_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('provisional', 'Provisional'), ('self_scheduling', 'Self-scheduling'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('live', 'Live'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
