# Generated by Django 6.0.3 on 2026-03-13 02:08

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    Survey = apps.get_model("posts", "Survey")
    Survey.objects.filter(status="created").update(status="planned")
    Survey.objects.filter(status="completed").update(status="submitted")
    Survey.objects.filter(status="overdue").update(status="planned")


def reverse_statuses(apps, schema_editor):
    Survey = apps.get_model("posts", "Survey")
    Survey.objects.filter(status="planned").update(status="created")


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_survey_schedule_type_alter_survey_status'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_statuses),
    ]
