# Generated by Django 6.0.3 on 2026-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_surveysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
