# Generated by Django 6.0.3 on 2026-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_survey_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date_status',
            new_name='schedule_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='survey',
            name='visit_requirement',
            field=models.CharField(blank=True, choices=[('unrestricted', 'Unrestricted'), ('prearranged', 'Pre-arranged')], max_length=20, null=True),
        ),
    ]
