# Generated by Django 6.0.3 on 2026-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_rename_date_status_survey_schedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='arrival_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='departure_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='notify_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
