# Generated by Django 6.0.3 on 2026-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_survey_arrival_action_survey_departure_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_weekends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='window_end_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
