# Generated by Django 6.0.3 on 2026-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_survey_window_start_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='visit_requirement',
            field=models.CharField(blank=True, choices=[('unrestricted_notify', 'Unrestricted - notify in advance'), ('unrestricted', 'Unrestricted - no notification'), ('prearranged', 'Pre-arranged')], max_length=20, null=True),
        ),
    ]
