# Generated by Django 6.0.3 on 2026-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_add_unrestricted_notify_visit_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='visit_requirement',
            field=models.CharField(blank=True, choices=[('24h_notify', '24 Hours - notify in advance'), ('24h_no_notify', '24 Hours - no notification'), ('wh_notify', 'Working hours - notify in advance'), ('wh_no_notify', 'Working hours - no notification'), ('prearranged', 'Pre-arranged visits only')], max_length=20, null=True),
        ),
    ]
