# Generated by Django 6.0.3 on 2026-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_update_visit_requirement_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='attendance_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('attended', 'Attended'), ('missed', 'Missed')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='scheduled_status',
            field=models.CharField(blank=True, choices=[('self_scheduled', 'Self-scheduled'), ('provisional', 'Provisional'), ('confirmed', 'Confirmed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_date_status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled')], default='unscheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_record_status',
            field=models.CharField(choices=[('unarchived', 'Unarchived'), ('archived', 'Archived')], default='unarchived', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
