# Generated by Django 6.0.3 on 2026-03-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_backfill_domain_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsite',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
