# Generated by Django 6.0.3 on 2026-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_add_is_demo_to_site_survey_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='other_attendees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='site_requirements',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
